#  Copyright 2022 Nikita Petko <petko@vmminfra.net>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

FROM node:lts-alpine

ENV LOG_STARTUP_INFO=true
ENV HATE_LAN_ACCESS=true
ENV MFDLABS_ARC_SERVER=
ENV ALLOWED_IPV4_CIDRS=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
ENV ALLOWED_IPV6_CIDRS=fd00::/8,fe80::/10,ff00::/8,2001:db8::/32,fc00::/7,::1/128
ENV LOG_PERSIST=false
ENV ABORT_CONNECTION_IF_INVALID_IP=true
ENV GA4_MEASUREMENT_ID=
ENV GA4_API_SECRET=
ENV GA4_ENABLE_LOGGING=false
ENV GA4_ENABLE_VALIDATION=true
ENV GA4_DISABLE_IP_LOGGING=false
ENV ENABLE_GA4_CLIENT=false
ENV DISABLE_IPV6=true
ENV INSECURE_PORT=80
ENV SECURE_PORT=443
ENV ENABLE_TLS_SERVER=true
ENV BIND_ADDRESS_IPV4=0.0.0.0
ENV BIND_ADDRESS_IPV6=::
ENV ENABLE_TLSV2=false
ENV SPHYNX_REWRITE_FILE_NAME=sphynx-rewrite.yml
ENV SPHYNX_HARDCODE_FILE_NAME=sphynx-hardcode.yml
ENV SPHYNX_DOMAIN=apis.roblox.com
ENV SPHYNX_REWRITE_BASE_DIRECTORY=
ENV SPHYNX_REWRITE_RELOAD_ON_REQUEST=false
ENV SSL_BASE_DIRECTORY=
ENV SSL_CERTIFICATE_FILE_NAME=roblox-platform.crt
ENV SSL_KEY_FILE_NAME=roblox-platform.unencrypted.key
ENV SSL_CERTIFICATE_CHAIN_FILE_NAME=global-ca.crt
ENV SSL_KEY_PASSPHRASE=
ENV EXIT_ON_UNCAUGHT_EXCEPTION=true
ENV EXIT_ON_UNHANDLED_REJECTION=true
ENV LOG_TO_FILE_SYSTEM=false
ENV LOG_TO_CONSOLE=true
ENV LOG_LEVEL=info
ENV CORS_RULES_FILE_NAME=cors-rules.yml
ENV CORS_RULES_BASE_DIRECTORY=
ENV CORS_RULES_RELOAD_ON_REQUEST=false
ENV CORS_APPLY_HEADERS_REGARDLESS_OF_ORIGIN=false
ENV CORS_APPLY_HEADERS_REGARDLESS_OF_ORIGIN_HEADER=false
ENV REVERSE_PROXY_MIDDLEWARE_ENABLED=true
ENV AUTHORIZED_REVERSE_PROXY_IPV4_ADDRESSES=
ENV AUTHORIZED_REVERSE_PROXY_IPV6_ADDRESSES=
ENV USE_CLOUDFLARE_FORWARDING_HEADERS=false
ENV CLOUDFLARE_IPV4_ADDRESSES=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
ENV CLOUDFLARE_IPV6_ADDRESSES=2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
ENV FORWARDING_HEADER_NAME=X-Forwarded-For
ENV REVERSE_PROXY_MIDDLEWARE_REASSIGN_CLIENT_IP_ADDRESS=true
ENV REVERSE_PROXY_MIDDLEWARE_REASSIGN_HOST_HEADER=false
ENV FORWARDING_TRANSFORMED_HOST_HEADER_NAME=X-Forwarded-Host
ENV REVERSE_PROXY_MIDDLEWARE_REASSIGN_CLIENT_SCHEME=true
ENV FORWARDING_SCHEME_HEADER_NAME=X-Forwarded-Proto
ENV REVERSE_PROXY_MIDDLEWARE_REASSIGN_CLIENT_PORT=true
ENV FORWARDING_PORT_HEADER_NAME=X-Forwarded-Port
ENV USE_HEALTH_CHECK_MIDDLEWARE=true
ENV ARC_MACHINE_INFO_URL=http://lb-services.ops-dev.vmminfra.dev/ui/machine/%s/summary
ENV REQUEST_EXTENSIONS_ENABLE_GOOGLE_ANALYTICS=false
ENV HOSTNAME_RESOLUTION_MIDDLEWARE_STRIP_PORT_FROM_HOST_HEADER=true
ENV ROBLOX_TEST_SITE_DOMAIN_REGEX=(([a-z0-9\.]{0,255})\.)?((site|game)test[1-5])\.(roblox(labs)?|simul(ping|pong|prod))\.(com|local)
ENV ROBLOX_PRODUCTION_APEX_DOMAIN=roblox.com
ENV ENABLE_CORS_WRITER=true
ENV SEND_AXIOS_REQUEST_WITH_FORWARDED_HEADERS=true
ENV SEND_AXIOS_REQUEST_TIMEOUT=35000
ENV DEBUG_ECHO_REQUEST_CONFIG=false
ENV ENABLE_CERTIFICATE_VALIDATION=false
ENV HEALTH_CHECK_PATH=/_lb/_/health

# make the 'app' folder the current working directory
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production
RUN npm run build-full

CMD [ "npm", "start" ]